# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExcelDataExporter
                                 A QGIS plugin
 Excel Data Exporter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-01
        copyright            : (C) 2021 by N/A
        email                : N/A
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExcelDataExporter class from file ExcelDataExporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Excel_Data_Exporter import ExcelDataExporter
    return ExcelDataExporter(iface)
